# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "AngouriMath"; version = "1.4.0-preview.3"; sha256 = "088ij3jps5wkshw5d39mrkvf06jxvkqwkpxg30ipcp8958f23nyx"; })
  (fetchNuGet { pname = "Antlr4.Runtime.Standard"; version = "4.9.2"; sha256 = "0gd1w9h7qs52kilkkz532nxcvvqy26fmilpr9vk2q9ww8qr10s8f"; })
  (fetchNuGet { pname = "GenericTensor"; version = "1.0.4"; sha256 = "0am2s5216cz4rzf3j44c6hravi0va13dxsba89v7c530z485mmai"; })
  (fetchNuGet { pname = "HonkSharp"; version = "1.0.3"; sha256 = "09nh52g7mdw8mvgr5z6z2f4kdsscvsb7m7mmsx3vwfizwa8f31p4"; })
  (fetchNuGet { pname = "PeterO.Numbers"; version = "1.8.0"; sha256 = "0s454mc0yv1vnpb80paj35znpkx2471h6aradj3mmh5dnsrzw8wh"; })
]
